# Generated by Django 4.2.20 on 2025-05-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='PostTag',
        ),
    ]
