# Generated by Django 4.2.20 on 2025-05-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_tag_posttag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
