# Generated by Django 4.2.20 on 2025-04-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_link_rename_settings_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='SiteInfo',
        ),
    ]
