# Generated by Django 4.2.20 on 2025-04-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_setting_siteinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'SiteInfo', 'verbose_name_plural': 'SiteInfos'},
        ),
    ]
