# Generated by Django 4.2.20 on 2025-04-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_link_options_alter_siteinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'SiteInfo'},
        ),
    ]
