# Generated by Django 4.2.20 on 2025-04-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_link_options_alter_siteinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'managed': False, 'verbose_name_plural': 'SiteInfo'},
        ),
    ]
