# Generated by Django 4.2.20 on 2025-04-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_siteinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'SiteInfo'},
        ),
    ]
