# Generated by Django 4.2.20 on 2025-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_siteinfo_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
