# Generated by Django 4.2.20 on 2025-04-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertybook_children_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyreview',
            options={'ordering': ['created_at']},
        ),
    ]
