# Generated by Django 4.2.20 on 2025-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_place_image_alter_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
    ]
