# Generated by Django 4.2.20 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_servicessection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
