# Generated by Django 4.2.20 on 2025-04-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_servicessection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessection',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='property_service', to='property.property'),
            preserve_default=False,
        ),
    ]
