# Generated by Django 4.2.20 on 2025-04-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_servicessection_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicessection',
            name='property',
        ),
    ]
