# Generated by Django 4.2.20 on 2025-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_servicessection_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
